: 'experiment_name=multi-source-single-target-digit-five
dataset=digit-five
num_targets=1
num_exclude=0
num_iter=10
epochs=1
rounds=1000
batch_size=128
lr=0.005
lr_decay_rate=0.75
num_identical_domain_clients=1
finetune=yes'


screen -dmS digit-five_mnistm_0_1_1000 sh -c 'docker run --gpus \"device=0\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=mnistm --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_mnist_0_1_1000 sh -c 'docker run --gpus \"device=1\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_0_1_1000 sh -c 'docker run --gpus \"device=2\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_syn_0_1_1000 sh -c 'docker run --gpus \"device=3\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=syn --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_usps_0_1_1000 sh -c 'docker run --gpus \"device=4\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=usps --exclude_domains= --num_iter=0 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_mnistm_1_1_1000 sh -c 'docker run --gpus \"device=5\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=mnistm --exclude_domains= --num_iter=1 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_mnist_1_1_1000 sh -c 'docker run --gpus \"device=6\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=1 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_1_1_1000 sh -c 'docker run --gpus \"device=7\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=1 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'

screen -dmS digit-five_syn_1_1_1000 sh -c 'docker run --gpus \"device=0\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=syn --exclude_domains= --num_iter=1 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_usps_1_1_1000 sh -c 'docker run --gpus \"device=1\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=usps --exclude_domains= --num_iter=1 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_mnistm_2_1_1000 sh -c 'docker run --gpus \"device=2\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=mnistm --exclude_domains= --num_iter=2 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_mnist_2_1_1000 sh -c 'docker run --gpus \"device=3\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=2 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_2_1_1000 sh -c 'docker run --gpus \"device=4\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=2 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_syn_2_1_1000 sh -c 'docker run --gpus \"device=5\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=syn --exclude_domains= --num_iter=2 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_usps_2_1_1000 sh -c 'docker run --gpus \"device=6\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=usps --exclude_domains= --num_iter=2 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_mnistm_3_1_1000 sh -c 'docker run --gpus \"device=7\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=mnistm --exclude_domains= --num_iter=3 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'

screen -dmS digit-five_mnist_3_1_1000 sh -c 'docker run --gpus \"device=0\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=3 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_3_1_1000 sh -c 'docker run --gpus \"device=1\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=3 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_syn_3_1_1000 sh -c 'docker run --gpus \"device=2\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=syn --exclude_domains= --num_iter=3 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_usps_3_1_1000 sh -c 'docker run --gpus \"device=3\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=usps --exclude_domains= --num_iter=3 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_mnistm_4_1_1000 sh -c 'docker run --gpus \"device=4\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=mnistm --exclude_domains= --num_iter=4 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_mnist_4_1_1000 sh -c 'docker run --gpus \"device=5\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=4 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_4_1_1000 sh -c 'docker run --gpus \"device=6\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=4 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_syn_4_1_1000 sh -c 'docker run --gpus \"device=7\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=syn --exclude_domains= --num_iter=4 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'

screen -dmS digit-five_usps_4_1_1000 sh -c 'docker run --gpus \"device=0\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=usps --exclude_domains= --num_iter=4 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_mnistm_5_1_1000 sh -c 'docker run --gpus \"device=1\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=mnistm --exclude_domains= --num_iter=5 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_mnist_5_1_1000 sh -c 'docker run --gpus \"device=2\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=5 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_5_1_1000 sh -c 'docker run --gpus \"device=3\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=5 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_syn_5_1_1000 sh -c 'docker run --gpus \"device=4\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=syn --exclude_domains= --num_iter=5 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_usps_5_1_1000 sh -c 'docker run --gpus \"device=5\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=usps --exclude_domains= --num_iter=5 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_mnistm_6_1_1000 sh -c 'docker run --gpus \"device=6\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=mnistm --exclude_domains= --num_iter=6 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_mnist_6_1_1000 sh -c 'docker run --gpus \"device=7\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=6 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'

screen -dmS digit-five_svhn_6_1_1000 sh -c 'docker run --gpus \"device=0\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=6 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_syn_6_1_1000 sh -c 'docker run --gpus \"device=1\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=syn --exclude_domains= --num_iter=6 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_usps_6_1_1000 sh -c 'docker run --gpus \"device=2\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=usps --exclude_domains= --num_iter=6 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_mnistm_7_1_1000 sh -c 'docker run --gpus \"device=3\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=mnistm --exclude_domains= --num_iter=7 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_mnist_7_1_1000 sh -c 'docker run --gpus \"device=4\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=7 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_7_1_1000 sh -c 'docker run --gpus \"device=5\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=7 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_syn_7_1_1000 sh -c 'docker run --gpus \"device=6\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=syn --exclude_domains= --num_iter=7 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_usps_7_1_1000 sh -c 'docker run --gpus \"device=7\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=usps --exclude_domains= --num_iter=7 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'

screen -dmS digit-five_mnistm_8_1_1000 sh -c 'docker run --gpus \"device=0\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=mnistm --exclude_domains= --num_iter=8 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_mnist_8_1_1000 sh -c 'docker run --gpus \"device=1\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=8 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_8_1_1000 sh -c 'docker run --gpus \"device=2\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=8 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_syn_8_1_1000 sh -c 'docker run --gpus \"device=3\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=syn --exclude_domains= --num_iter=8 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_usps_8_1_1000 sh -c 'docker run --gpus \"device=4\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=usps --exclude_domains= --num_iter=8 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_mnistm_9_1_1000 sh -c 'docker run --gpus \"device=5\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=mnistm --exclude_domains= --num_iter=9 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_mnist_9_1_1000 sh -c 'docker run --gpus \"device=6\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=mnist --exclude_domains= --num_iter=9 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_svhn_9_1_1000 sh -c 'docker run --gpus \"device=7\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=svhn --exclude_domains= --num_iter=9 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'

screen -dmS digit-five_syn_9_1_1000 sh -c 'docker run --gpus \"device=0\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=syn --exclude_domains= --num_iter=9 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
screen -dmS digit-five_usps_9_1_1000 sh -c 'docker run --gpus \"device=1\"  -it --rm -u `id -u $USER` -v $SOURCE_PATH_FACT:/mnt fact python3 /mnt/FACT.py --dataset=digit-five --target=usps --exclude_domains= --num_iter=9 --epochs=1 --rounds=1000 --batch_size=128 --lr=0.005 --name=multi-source-single-target-digit-five --test_source=no --test_target=yes --lr_decay_rate=0.75 --num_identical_domain_clients=1 --finetune=yes; exec bash'
